### ISSUE TITLE
Estaciones a geojson

### ISSUE THREAD

**Issue by edgaregurrola** [lac-analytics/gdlaire#8]

**Comment by edgaregurrola** [comment]
Ya tengo el geojson, lo hice en QGIS, lo iba a subir haciendo un commit, pero no sé si quieras que te lo pase por correo mejor @nateraluis

**Comment by nateraluis** [comment]
Mejor aparte, modifique el .gitignore para que no haga tracking de lo que esté en data/ porque github no puede con archivos pesados.
